"""Create jobs table

Revision ID: 10624d0381a6
Revises: 
Create Date: 2018-11-26 13:28:26.003155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10624d0381a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('job_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('runfolder', sa.String(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('NONE', 'PENDING', 'READY', 'STARTED', 'DONE', 'ERROR', 'CANCELLED', name='status'), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    # ### end Alembic commands ###
