"""Adding log field

Revision ID: cb2de95ba237
Revises: 3d88ffdab829
Create Date: 2019-04-01 10:40:05.384911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb2de95ba237'
down_revision = '3d88ffdab829'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('log', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'log')
    # ### end Alembic commands ###
